### ISSUE TITLE
Add pre-commit hook to catch @todo

### ISSUE THREAD

**Issue by EvanHerman** [godaddy-wordpress/go#292]
It would be nice if we could setup a pre-commit hook (or a grunt task?) that scans our files for any `@todo` and then either lists out those files or asks for confirmation before continuing with the commit.

This would help us ensure that we have all of our `@todo` completed before releasing a new version.

**Priority** (select one):
- [ ] High - Functional blocker
- [ ] Medium - Doesn't work as expected 
- [x] Low - Not a big deal but we'd want to get to this eventually
